### PR TITLE
For next

### PR DESCRIPTION
**Pull request by hclee**

### CODE REVIEW

**Comment by namjaejeon** [comment]
cifs/001 test hang issue happen.

**Comment by hclee** [comment]
> cifs/001 test hang issue happen.

I had run xfstests for kernel v5.4. I will check it.

**Comment by namjaejeon** [comment]
Can I know what patch should be committed first ? namespace or ksmbd_lock ?

**Comment by hclee** [comment]
> Can I know what patch should be committed first ? namespace or ksmbd_lock ?

Namespace please. I wrote the ksmbd_lock patch based on the namespace patch.

**Comment by namjaejeon** [comment]
ok

**Comment by namjaejeon** [comment]
re-run travis-CI now. Let me check the result.

**Comment by namjaejeon** [comment]
same hang issue happen..

**Comment by hclee** [comment]
> same hang issue happen..

I will check it.

**Pull request closed without merging**
